language: julia
os:
  - osx
  - linux
julia:
  - 1.2
notifications:
  email: false
# script:
#   - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#   - julia -e 'Pkg.clone(pwd()); Pkg.build("ReusableFunctions"); Pkg.test("ReusableFunctions"; coverage=true)';
after_success:
  - julia -e 'import Pkg; import ReusableFunctions; cd(joinpath(dirname(pathof(ReusableFunctions)))); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(Codecov.process_folder())'
